In [14]:
int_text = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
print(int_text)
print(len(int_text))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
15


In [22]:
batch_size = 2
seq_length = 3

# Compute number of batches.
n_batches = len(int_text)//(batch_size*seq_length)
print(n_batches)

833


In [23]:
int_text = range(5000)
print(len(int_text))

5000


In [24]:
batch_size = 128
seq_length = 5

# Compute number of batches.
n_batches = len(int_text)//(batch_size*seq_length)
print(n_batches)

7


In [25]:
# The target is lagged by an offset of 1. So, if
# len(int_text) = n_batches*batch_size*seq_length,
# we won't have enough data for the last target!
# We want only full batches. So, if
# len(int_text) = n_batches*batch_size*seq_length,
# DECREMENT n_batches by 1.
if len(int_text) == n_batches*batch_size*seq_length:
    n_batches -= 1
print(n_batches)

7


In [27]:
import numpy as np

# Loop over BATCHES.
batches = np.ndarray((n_batches,2,batch_size,seq_length)) # Initialize output numpy ndarray.
for batch_num in range(n_batches):
    print(batch_num)
    input_seq  = [] # Initialize list of input  sequences within batch.
    target_seq = [] # Initialize list of target sequences within batch.
    # Loop over SEQUENCES within batch.
    for seq_num in range(batch_size):
        # Grab the next input and target sequences.
        idx1 = (batch_num*seq_length) + (seq_num*seq_length)
        idx2 = idx1 + seq_length
        idy1 = idx1 + 1
        idy2 = idy1 + seq_length
        batches[batch_num,0,seq_num,] = int_text[idx1:idx2]
        batches[batch_num,1,seq_num,] = int_text[idy1:idy2]
print(batches)

0
1
2
3
4
5
6
[[[[   0.    1.    2.    3.    4.]
   [   5.    6.    7.    8.    9.]
   [  10.   11.   12.   13.   14.]
   ..., 
   [ 625.  626.  627.  628.  629.]
   [ 630.  631.  632.  633.  634.]
   [ 635.  636.  637.  638.  639.]]

  [[   1.    2.    3.    4.    5.]
   [   6.    7.    8.    9.   10.]
   [  11.   12.   13.   14.   15.]
   ..., 
   [ 626.  627.  628.  629.  630.]
   [ 631.  632.  633.  634.  635.]
   [ 636.  637.  638.  639.  640.]]]


 [[[   5.    6.    7.    8.    9.]
   [  10.   11.   12.   13.   14.]
   [  15.   16.   17.   18.   19.]
   ..., 
   [ 630.  631.  632.  633.  634.]
   [ 635.  636.  637.  638.  639.]
   [ 640.  641.  642.  643.  644.]]

  [[   6.    7.    8.    9.   10.]
   [  11.   12.   13.   14.   15.]
   [  16.   17.   18.   19.   20.]
   ..., 
   [ 631.  632.  633.  634.  635.]
   [ 636.  637.  638.  639.  640.]
   [ 641.  642.  643.  644.  645.]]]


 [[[  10.   11.   12.   13.   14.]
   [  15.   16.   17.   18.   19.]
   [  20.   21.   22.   23. 